# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://tiliatranslations.it
title: Tilia Translations di Angela Brisotto
email: angela@tiliatranslations.it
author: Angela Brisotto
description: Traduttrice dall‚Äôinglese e dal polacco all‚Äôitaliano ¬∑ English & Polish to Italian translator ¬∑ T≈Çumaczka z angielskiego i z polskiego na w≈Çoski üìù

copyright: 'Copyright &copy; 2021 Tilia Translations di Angela Brisotto. All Rights Reserved.
<br>
<br>
TILIA TRANSLATIONS DI ANGELA BRISOTTO
<br>
<br>
Via Daniele Manin, n. 4/10
<br>
31027 Spresiano (TV)
<br>
P.IVA/VAT: 05247030264
<br>
Professionista di cui alla Legge n. 4 del 14.1.2013
<br>
<br>
<br>
Credits: Theme by <a href="https://startbootstrap.com/">Start Bootstrap</a>.'

credits: '&#9993; angela@tiliatranslations.it
<br>
<br>
Monday - Friday: 9 AM - 5 PM (CET)
<br>
<a href="https://www.proz.com/translator/2997713">Current availability</a>
<br>
<br>
Poniedzia≈Çek - PiƒÖtek: 9.00 - 17.00 (CET)
<br>
<a href="https://www.proz.com/translator/2997713">M√≥j kalendarz</a>
<br>
<br>
Luned√¨ - Venerd√¨: 9.00 - 17.00 (CET)
<br>
<a href="https://www.proz.com/translator/2997713">Calendario aggiornato</a>'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/in/angela-brisotto
  - title: email
    url: mailto:angela@tiliatranslations.it
  - title: proz
    url: https://www.proz.com/translator/2997713
  - title: bonsai
    url: https://joinbonsai.co/angelabrisotto/
